name: unspider
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - gdal=3.0.1
  - numpy=1.15.*
  - matplotlib
  - ipython
  - jupyter
  - ipywidgets
  - tqdm
  - imageio
  - ipyleaflet
  - ipyfilechooser
  - jupyter_contrib_nbextensions
